### ISSUE TITLE
Help! OverflowError: cannot convert float infinity to integer

### ISSUE THREAD

**Issue by hukui4860** [VemundFredriksen/LungTumorMask#4] opened 2023-04-05 12:14 UTC
# my package list:
# Name                    Version                   Build  Channel
blas                      1.0                         mkl  
ca-certificates           2022.12.7            h033912b_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37h7346b73_1    conda-forge
cycler                    0.11.0                   pypi_0    pypi
fastremap                 1.13.4                   pypi_0    pypi
fill-voids                2.0.3                    pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
future                    0.18.2           py37hf985489_5    conda-forge
imageio                   2.26.0                   pypi_0    pypi
intel-openmp              2022.1.0          haf03e11_3719  
kiwisolver                1.4.4                    pypi_0    pypi
libblas                   3.9.0           1_h508aa58_netlib    conda-forge
libcblas                  3.9.0           5_h0661a58_netlib    conda-forge
libcxx                    14.0.6               h9765a3e_0  
libffi                    3.4.2                hecd8cb5_6  
libgfortran               5.0.0           11_3_0_h97931a8_31    conda-forge
libgfortran5              12.2.0              he409387_31    conda-forge
liblapack                 3.9.0           5_h0661a58_netlib    conda-forge
libopenblas               0.3.21          openmp_h429af6e_3    conda-forge
libprotobuf               3.20.3               hfff2838_0  
libuv                     1.44.2               hac89ed1_0    conda-forge
llvm-openmp               16.0.0               h61d9ccf_0    conda-forge
lungmask                  0.2.13                   pypi_0    pypi
lungtumormask             1.1.0                    pypi_0    pypi
matplotlib                3.5.3                    pypi_0    pypi
mkl                       2019.4                      233  
mkl-service               2.3.0            py37h9ed2024_0  
mkl_fft                   1.3.0            py37ha059aab_0  
mkl_random                1.1.1            py37h959d312_0  
monai                     1.1.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcec6c5f_0  
networkx                  2.6.3                    pypi_0    pypi
nibabel                   4.0.2                    pypi_0    pypi
ninja                     1.11.1               hb8565cd_0    conda-forge
numpy                     1.21.6           py37h345d48f_0    conda-forge
openssl                   1.1.1t               hfd90126_0    conda-forge
packaging                 23.0                     pypi_0    pypi
pillow                    9.5.0                    pypi_0    pypi
pip                       22.3.1           py37hecd8cb5_0  
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydicom                   2.3.1                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
python                    3.7.16               h218abb5_0  
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.12.1          cpu_py37h64f2f56_1  
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0              py37h69ee0a8_4    conda-forge
readline                  8.2                  hca72f7f_0  
scikit-image              0.15.0                   pypi_0    pypi
scipy                     1.7.3            py37h4e3cf02_0    conda-forge
setuptools                65.6.3           py37hecd8cb5_0  
simpleitk                 2.2.1                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.41.1               h6c40b1e_0  
tk                        8.6.12               h5d9f67b_0  
torch                     1.2.0                    pypi_0    pypi
torchvision               0.4.0                    pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
wheel                     0.38.4           py37hecd8cb5_0  
xz                        5.2.10               h6c40b1e_1  
yaml                      0.2.5                h0d85af4_2    conda-forge
zlib                      1.2.13               h4dc903c_0  

(LungTumorMask) hk LungTumorMask % lungtumormask CHENCHANGMIN.nii CHENCHANGMIN_mask.nii
Loading model...
Preprocessing image...
Segmenting lungs...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 67/67 [04:42<00:00,  4.22s/it]
0it [00:00, ?it/s]
/Users/hk/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/monai/utils/deprecate_utils.py:107: FutureWarning: <class 'monai.transforms.utility.array.AddChannel'>: Class `AddChannel` has been deprecated since version 0.8. please use MetaTensor data type and monai.transforms.EnsureChannelFirst instead.
  warn_deprecated(obj, msg, warning_category)
Traceback (most recent call last):
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/bin/lungtumormask", line 8, in <module>
    sys.exit(main())
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungtumormask/__main__.py", line 20, in main
    mask.mask(args.input, args.output)
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungtumormask/mask.py", line 23, in mask
    preprocess_dump = preprocess(image_path)
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungtumormask/dataprocessing.py", line 152, in preprocess
    right_lung_processed = process_lung_scan(scan_dict, right_lung_extreme)
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungtumormask/dataprocessing.py", line 110, in process_lung_scan
    SpatialCropd(keys=["image"], roi_start=(extremes[0][0], extremes[1][0], extremes[2][0]), roi_end=(extremes[0][1], extremes[1][1], extremes[2][1])),
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/monai/transforms/croppad/dictionary.py", line 400, in __init__
    cropper = SpatialCrop(roi_center, roi_size, roi_start, roi_end, roi_slices)
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/monai/transforms/croppad/array.py", line 502, in __init__
    roi_center=roi_center, roi_size=roi_size, roi_start=roi_start, roi_end=roi_end, roi_slices=roi_slices
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/monai/transforms/croppad/array.py", line 418, in compute_slices
    roi_start_t = convert_to_tensor(data=roi_start, dtype=torch.int16, wrap_sequence=True)
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/monai/utils/type_conversion.py", line 166, in convert_to_tensor
    tuple_ret = tuple(convert_to_tensor(i, dtype=dtype, device=device, track_meta=track_meta) for i in data)
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/monai/utils/type_conversion.py", line 166, in <genexpr>
    tuple_ret = tuple(convert_to_tensor(i, dtype=dtype, device=device, track_meta=track_meta) for i in data)
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/monai/utils/type_conversion.py", line 161, in convert_to_tensor
    return _convert_tensor(data, dtype=dtype, device=device)
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/monai/utils/type_conversion.py", line 138, in _convert_tensor
    tensor = torch.as_tensor(tensor, **kwargs)
OverflowError: cannot convert float infinity to integer

Please help me with this problem, Thanks!

**Comment by andreped** [comment] 2023-04-05 13:27
Hello. Let me run some unit tests to see if I can reproduce the issue.

I just noticed that we have not set any versioning in the dependencies, which likely is causing this issue.

**Comment by hukui4860** [comment] 2023-04-05 13:55
here also one problem in :   File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungtumormask/dataprocessing.py", line 52, in mask_lung
    ## outmask = lungmask.utils.postrocessing(timage_res)
AttributeError: module 'lungmask.utils' has no attribute 'postrocessing'

letter p missed: outmask = lungmask.utils.postprocessing(timage_res)

**Comment by andreped** [comment] 2023-04-05 14:00
Just fixed it: https://github.com/VemundFredriksen/LungTumorMask/commit/1ddaffdab33fdc5e74b1346702b1a2a3ebc3d658

In the old version of `lungmask` there was a typo in the API. As we did not have versioning on dependencies, the API had changed.

**Comment by hukui4860** [comment] 2023-04-05 14:08
> Just fixed it: [1ddaffd](https://github.com/VemundFredriksen/LungTumorMask/commit/1ddaffdab33fdc5e74b1346702b1a2a3ebc3d658)
> 
> In the old version of `lungmask` there was a typo in the API. As we did not have versioning on dependencies, the API had changed.

Thanks! I just checked the API, that typo was corrected now.

**Comment by hukui4860** [comment] 2023-04-05 14:29
> Hello. Let me run some unit tests to see if I can reproduce the issue.
> 
> I just noticed that we have not set any versioning in the dependencies, which likely is causing this issue.

If U solved the error by specialized version of some packages, please add an updated file "requirements.txt" for both ‘lungmask’ and ‘LungTumorMask’ in one file,  that would be very helpful to me, I'm a fresh about python. Thanks very much

**Comment by hukui4860** [comment] 2023-04-05 14:31
> All unit tests seem to pass now (see [here](https://github.com/VemundFredriksen/LungTumorMask/actions/runs/4619375704/jobs/8168053306)).
> 
> Hence, I am unable to reproduce this, but I made some changes. Could you try installing from the current state?
> 
> ```
> pip uninstall lungtumormask 
> pip install git+https://github.com/VemundFredriksen/LungTumorMask
> ```

I will try it now, thanks! if there is any problem, I hope your replying, thanks again!

**Comment by andreped** [comment] 2023-04-05 14:32
> If U solved the error by specialized version of some packages, please add an updated file "requirements.txt" for both ‘lungmask’ and ‘LungTumorMask’ in one file

This is all handled [here](https://github.com/VemundFredriksen/LungTumorMask/blob/main/setup.py#L11). Right now, we also use my own fork of lungmask, which should be fixed. 

We will inherit whichever dependencies lungmask had at that state. We do not need to install the dependencies separately using a `requirements.txt` file, this is handled by the package.

**Comment by hukui4860** [comment] 2023-04-05 14:46
> > If U solved the error by specialized version of some packages, please add an updated file "requirements.txt" for both ‘lungmask’ and ‘LungTumorMask’ in one file
> 
> This is all handled [here](https://github.com/VemundFredriksen/LungTumorMask/blob/main/setup.py#L11). Right now, we also use my own fork of lungmask, which should be fixed.
> 
> We will inherit whichever dependencies lungmask had at that state. We do not need to install the dependencies separately using a `requirements.txt` file, this is handled by the package.

That's great! U are so awesome! I'm a fresher about programming, I learn python for AI in medicine recently, your comments delivered me so much!

**Comment by hukui4860** [comment] 2023-04-05 15:03
> All unit tests seem to pass now (see [here](https://github.com/VemundFredriksen/LungTumorMask/actions/runs/4619375704/jobs/8168053306)).
> 
> Hence, I am unable to reproduce this, but I made some changes. Could you try installing from the current state?
> 
> ```
> pip uninstall lungtumormask 
> pip install git+https://github.com/VemundFredriksen/LungTumorMask
> ```

I have  uninstall and install as you told me, but new error occurred: 

(LungTumorMask) caiqian890307@hk LungTumorMask % lungtumormask CHENCHANGMIN.nii CHENCHANGMIN_mask.nii
Traceback (most recent call last):
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/bin/lungtumormask", line 5, in <module>
    from lungtumormask.__main__ import main
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungtumormask/__main__.py", line 4, in <module>
    from lungtumormask import mask
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungtumormask/mask.py", line 2, in <module>
    from lungtumormask.dataprocessing import preprocess, post_process
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungtumormask/dataprocessing.py", line 2, in <module>
    from lungmask import mask
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungmask/mask.py", line 3, in <module>
    from lungmask import utils
  File "/Users/caiqian890307/anaconda3/envs/LungTumorMask/lib/python3.7/site-packages/lungmask/utils.py", line 4, in <module>
    from torch.utils.data import Dataset
ImportError: cannot import name 'Dataset' from 'torch.utils.data' (unknown location)

**Comment by andreped** [comment] 2023-04-05 16:00
Might be because of something your have preinstalled with Anaconda.

Just to be sure, could you try using regular Python (without conda)?

On Windows, I would think you have a Python version installed. Try writing `python -V` (or `py -V`) in the terminal.

If so, setup virtual environment by:
```
python -m pip install virtualenv
python -m virtualenv -ppython3 venv --clear
./venv/bin/activate

python -m pip install git+https://github.com/VemundFredriksen/LungTumorMask
```

Then try again and let me know how it goes.

**Comment by andreped** [comment] 2023-04-12 09:58
As you made a new issue https://github.com/VemundFredriksen/LungTumorMask/issues/5, where you were able to run lungtumormask, I believe this issue can be closed?

Closing for now. If you did something else than above, please let me know.

**Closed by andreped** 2023-04-12 09:58 UTC
Labels: bug
