### ISSUE TITLE
Some question after software used!

### ISSUE THREAD

**Issue by hukui4860** [VemundFredriksen/LungTumorMask#8] opened 2023-04-23 07:01 UTC
test 1: this is mask was derived from CT volumn without contrast agent enhanced.
![image](https://user-images.githubusercontent.com/25789684/233824033-f41de8a7-4647-4460-a49d-a9bd9bd45cf9.png)
![image](https://user-images.githubusercontent.com/25789684/233824093-938e8146-98c9-4a65-870a-09e23c50b8bb.png)
test2: this is mask was derived from Contrast agent enhanced CT images!
![image](https://user-images.githubusercontent.com/25789684/233824132-d3cee5cf-4d28-48d8-b305-15d4374e0df5.png)
why there are so much holes in the mask of tumor? However there isn't holes in your two examples displayed on this website.
And, CT without contrast agent enhanced image or CT with contrast agent enhanced image should I use for better mask? All thickness of my image was 5 mm

**Comment by andreped** [comment] 2023-04-23 08:51
Thickness quite large so it is likely due to some interpolation artifacts. I could take a look.

**Comment by hukui4860** [comment] 2023-04-23 09:07
> Thickness quite large so it is likely due to some interpolation artifacts. I could take a look.

test 1: thickness 0.625 mm with contrast agent enhanced
![0 625 CECT](https://user-images.githubusercontent.com/25789684/233830150-a24b5e2b-39d8-48f3-8882-060bd430e593.png)
![image](https://user-images.githubusercontent.com/25789684/233830460-0dd8d26b-46f3-453b-868c-34274dbef1a8.png)

test 2: thickness 0.625 mm with none contrast agent enhanced
![0 625 noneCE](https://user-images.githubusercontent.com/25789684/233830155-6d11c175-fe24-48a5-ab53-2c2ff0857313.png)
![image](https://user-images.githubusercontent.com/25789684/233830397-a5b79a27-7589-4e94-9f16-9e96f255910b.png)

I used thickness of 0.625 mm, holes still！

**Comment by hukui4860** [comment] 2023-04-23 09:08
> Thickness quite large so it is likely due to some interpolation artifacts. I could take a look.
> 
> EDIT: Which software did you use for rendering? ITK-Snap?

yes! ITK-Snap Version 3.6.0.

**Comment by andreped** [comment] 2023-04-23 09:32
Since you are observing this with both softwares, I believe the threshold set in the software might not be ideal.

I can add an argument to the CLI such that you can set this yourself. I will change the default from 0.5 to 0.4 and you can let me know how it works. Alternatively, it is required to do some post-processing before resampling the volume.

I was not the one to implement how the segmentations were handled from prediction to save on disk, so I am not sure what could be wrong. Can take a look though.

**Comment by andreped** [comment] 2023-04-23 09:37
From what I can see, we are thresholding before resampling, which could result in interpolation artifacts. Interpolating volumes in the logit domain is generally better but is slower (see [here](https://github.com/VemundFredriksen/LungTumorMask/blob/main/lungtumormask/dataprocessing.py#L235)).

**Comment by andreped** [comment] 2023-04-23 10:06
Added support for setting threshold and changed default threshold from 0.5 to 0.4 in 12a7dfee9c8139e1b01783fd4b19da105a6f2c4a.

Then try to do this:
```
pip uninstall lungtumormask
pip install git+https://github.com/VemundFredriksen/LungTumorMask --upgrade

lungtumormask input_ct.nii.gz output_mask.nii.gz --threshold 0.3 --lung-filter
```

Here I have used a lower threshold and used lung mask filtering, as it is likely that there will be some silly candidates outside the lung for lower thresholds.

**Comment by hukui4860** [comment] 2023-04-23 13:30
> From what I can see, we are thresholding before resampling, which could result in interpolation artifacts. Interpolating volumes in the logit domain is generally better but is slower (see [here](https://github.com/VemundFredriksen/LungTumorMask/blob/main/lungtumormask/dataprocessing.py#L235)).
> 
> Do you have a single CT to share with me, which I could use for debugging this? I do not have any appropriate CT volumes right now.

here is a nii file that i used for test.
[CHENG SHI MING CE 5.nii.gz](https://github.com/VemundFredriksen/LungTumorMask/files/11303841/CHENG.SHI.MING.CE.5.nii.gz)

**Comment by andreped** [comment] 2023-04-23 13:40
> here is a nii file that i used for test.
> [CHENG SHI MING CE 5.nii.gz](https://github.com/VemundFredriksen/LungTumorMask/files/11303841/CHENG.SHI.MING.CE.5.nii.gz)

I managed to reproduce the issue. Also with threshold=0.4.

I believe this is an interpolation artifact. Will try with smaller threshold first, just to see.

**Comment by hukui4860** [comment] 2023-04-23 13:56
> > here is a nii file that i used for test.
> > [CHENG SHI MING CE 5.nii.gz](https://github.com/VemundFredriksen/LungTumorMask/files/11303841/CHENG.SHI.MING.CE.5.nii.gz)
> 
> I managed to reproduce the issue. Also with threshold=0.4.
> 
> I believe this is an interpolation artifact. Will try with smaller threshold first, just to see.
> 
> EDIT: I observed the same with threshold=0.3. Will try some things.

threshold=0.3 does't work on my data!

**Comment by andreped** [comment] 2023-04-23 13:58
> threshold=0.3 does't work on my data!

I noticed the same. This is not a thresholding value issue, but an interpolation issue. I have added a fix now. Will just run some more tests, then make a PR, run the necessary unit tests to verify that it works across all relevant operating systems and python versions.

Will let you know when you can try again. Will revert back to default threshold of 0.5 then, if everything works.

**Comment by andreped** [comment] 2023-04-23 14:17
What helped the most was resampling the volume with the original sigmoid output and then threshold after, as I mentioned as a possible solution earlier. This is a common solution to this issue.

I also added a 3D morphology post-processing filter, but it does not seem to do much. Might have to apply 2D morphology operations on individual 2D frames, but in that case I would need to run a benchmark to assess whether it actually produces better segmentations overall and not just for this one CT; as well as which kernel radius is the most optimal.

Don't have time for all that now. But the fragmentation issue should be solved. At least it is less prominent.

**Comment by andreped** [comment] 2023-04-23 14:19
Fixed in 19d05ecf68afad0e675c4df99656cf5d50f2f836.

Try to reinstall from source and run `lungtumormask` again :]

**Comment by andreped** [comment] 2023-04-23 14:47
Also made a new release:
https://github.com/VemundFredriksen/LungTumorMask/releases/tag/v1.1.3

Thanks for reporting these issues!

**Comment by andreped** [comment] 2023-04-23 15:30
Further went ahead and improved the morphological post-processing. Results should be a lot smoother now, without any severe holes within the segmentation. If you wish to test different radius values in the post-processing, you can do so through this:
```
lungtumormask input_ct.nii.gz output_mask.nii.gz --threshold 0.5 --lung-filter --radius 3
```

By default we do not perform any lungmask filtering (dont filter candidates outside lung), threshold is 0.5, and radius is set to 1. The example above shows how you could impact this.

I made a minor release including the latest changes:
https://github.com/VemundFredriksen/LungTumorMask/releases/tag/v1.2.0

**Comment by hukui4860** [comment] 2023-04-24 01:11
> Further went ahead and improved the morphological post-processing. Results should be a lot smoother now, without any severe holes within the segmentation. If you wish to test different radius values in the post-processing, you can do so through this:
> 
> ```
> lungtumormask input_ct.nii.gz output_mask.nii.gz --threshold 0.5 --lung-filter --radius 3
> ```
> 
> By default we do not perform any lungmask filtering (dont filter candidates outside lung), threshold is 0.5, and radius is set to 1. The example above shows how you could impact this.
> 
> I made a minor release including the latest changes: https://github.com/VemundFredriksen/LungTumorMask/releases/tag/v1.2.0

I tried again, there is no hole within mask now.

**Comment by andreped** [comment] 2023-04-24 04:59
> I tried again, there is no hole within mask now

Great! Feel free to report any other bugs or issues if you observe any :]

**Closed** 2023-04-24 04:59 UTC
Labels: bug
